# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://JETBLACKJD.github.io/
baseurl: /JETBLACKJD.github.io/
title: Jordan Dent
author: Jordan Dent
description: Personal blog and resume
avatar: profile.png
email: jordanjdent97@gmail.com
github: JETBLACKJD # username
twitter: JET_BLACKJD
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
